### ISSUE TITLE
ToDo Task List

### ISSUE THREAD

**Issue by nabil** [nabil/ptolemy#18]
- [ ] Refactor plugin type to eclipse-plugin
- [ ] Enhance Login screen to allow selection of different DB files
- [ ] Enhance Export Mechanism to export only selected accounts
